config/routes.rb
VideoDemo::Application.routes.draw do
  
  root :to => "members#index"
  
  devise_for :users
  devise_scope :user do
	get "/login" => "devise/sessions#create", :method => "get"
	get "/register" => "devise/registrations#new", :method => "get"
	get "/logout" => "devise/sessions#destroy", :method => "delete"
  end

  resources :profile, :only => ['update']
   
  resources :users, :only => ['index', 'show'] do
	resources :schedules, :only => ['index'] do
		resources :bookings, :only => ['create'], :path_names => { create: 'book' }
	end
	resources :categories, :only => ['update', 'destroy']
  end
  resources :broadcasts, :only => ['create', 'show', 'destroy']
  resources :members, :only => ['index', 'show']
  resources :portfolio, :only => ['create', 'update', 'destroy']
  resources :schedules, :only => ['create', 'update', 'destroy']
  #resources :bookings, :only => ['update', 'destroy']


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
	user ||= User.new # guest user
	
	if user.admin?
		can :manage, :all
	else
		can :read, :all
	end
	
  end
  
end

app/models/booking.rb
class Booking < ActiveRecord::Base

	belongs_to :user, :class_name => 'User'
	has_and_belongs_to_many :schedules, :class_name => 'Schedule'
	
end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base

	belongs_to :user, :class_name => 'User'
	
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :users, :class_name => 'User'
end

app/models/credit.rb
class Credit < ActiveRecord::Base
	belongs_to :user, :class_name => 'User', :foreign_key => 'id'
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

	self.table_name = 'portfolio'
	belongs_to :user, :class_name => 'User'
	
	has_attached_file :cover_image,
		:default_url => "/images/missing.png",
		:storage => :s3,
		:bucket => 'video-conference-demo'

	
	def cover_image_url
        cover_image.url(:original)
    end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	
	has_one :user, :class_name => 'User', :foreign_key => 'user_id'
	
	has_attached_file :avatar,
		:default_url => "/images/missing.png",
		:storage => :s3,
		:bucket => 'video-conference-demo'

	def avatar_url
        avatar.url(:original)
    end

end

app/models/role.rb
class Role < ActiveRecord::Base
   has_and_belongs_to_many :users, :class_name => 'User'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

	belongs_to :user, :class_name => 'User'
	has_and_belongs_to_many :bookings, :class_name => 'Booking'
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
		 
   has_and_belongs_to_many :role, :class_name => 'Role'
   has_one :profile, :class_name => 'Profile', :foreign_key => 'user_id'
   has_many :credits, :class_name => 'Credit', :foreign_key => 'user_id'
   has_and_belongs_to_many :categories, :class_name => 'Category'
   has_many :broadcasts, :class_name => 'Broadcast', :foreign_key => 'user_id'
   has_many :portfolios, :class_name => 'Portfolio', :foreign_key => 'user_id'
   has_many :schedules, :class_name => 'Schedule', :foreign_key => 'user_id'
   has_many :bookings, :class_name => 'Booking'
   
   before_create :role_detect
   before_create :profile_detect
   
   private
   def role_detect
		if self.role.blank?
			self.role << Role.find('3')
		end
   end
   
   private 
   def profile_detect
		build_profile 
   end

   
end

app/models/video.rb
class Video < ActiveRecord::Base

	belongs_to :user, :class_name => 'User'
	validates :name, presence: true
	
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/elements/_footer.html.erb
<div class="footer">
	<table class="content_wrapper">
		<tr>
			<td class="main_links">
				<%= link_to "home", root_path, :id => "home" %>
				<%= link_to "support", root_path, :id => "support" %>
				<%= link_to "pricing", root_path, :id => "pricing" %>
				<%= link_to "how it works", root_path, :id => "how" %>
				<%= link_to "terms of service", root_path, :id => "tos" %>
				<%= link_to "privacy", root_path, :id => "privacy" %>
			</td>
			<td>
				<p class="title">company</p>
				<p>xpress is a new way to talk to the people you love!</p>
				<p>the trail-blazers, leaders & inspirations in any area of life have a wealth of knowledge waiting to be unearthed & this is the perfect way to do it :)</p>
			</td>
			<td>
				<p class="title">join the fun!</p>
				<div class="links">
					<%= link_to image_tag("app_store.png"), "http://www.google.com" %>
					<%= link_to image_tag("google_store.png"), "http://www.google.com" %>
					<%= link_to image_tag("windows_store.png"), "http://www.google.com" %>
					<%= link_to image_tag("register_store.png"), register_path %>
				</div>
			</td>
			<td>
				<p class="title">connect</p>
				<div class="social_icons">
					<%= link_to "", "http://www.facebook.com", :id => "facebook" %><!--
					--!><%= link_to "", "http://www.facebook.com", :id => "twitter" %><!--
					--!><%= link_to "", "http://www.facebook.com", :id => "pinterest" %><!--
					--!><%= link_to "", "http://www.facebook.com", :id => "googleplus" %><!--
					--!><%= link_to "", "http://www.facebook.com", :id => "fusion" %><!--
					--!><%= link_to "", "http://www.facebook.com", :id => "tumblr" %>
				</div>
				<p class="title">say hi!</div>
			</td>
		</tr>
	</table>
</div>

app/views/elements/_header.html.erb
<div class="header">
	<div class="information <%= "user" if (user_signed_in?) %>">
		<div class="content_wrapper" style="position: relative;">
			<% if user_signed_in? %>
			
				<div class="title">
					<div class="main"><%= link_to "x.press", root_path %></div>
					<div class="sub">connect with your heroes & friends</div>
				</div>
		
				<div class="profile_options">
						<%= link_to number_to_currency(@credits_balance, :unit => "£"), users_path, :id => "credits" %>
						<%= link_to "", users_path, :id => "profile" %>
						<%= link_to "", logout_path, :id => "logout" %>
				</div>
			
			<% else %>
			
				<div class="welcome">
					<div class="blurb">
						<p class="title">Welcome!</p>
						<p>x.press connects you with your favourite celebrities & experts in every area of life</p>
						<p>learn the insider tricks & get inside the head of your heroes! our cross-platform video & audio streaming app connects you wherever you are</p>
					</div>
				</div>
			
				<div class="user_options">
						<%= link_to "Login", login_path, id: "login", :class => "big_button" %>
						<%= link_to "Register", register_path, id: "register", :class => "big_button" %>
				</div>
				
				<div class="clear">&nbsp;</div>
			<% end %>
		</div>
	</div>
	
	<div class="nav_bar">
		<div id="links" <%= if (@members || current_page?(root_path)) then "class=active" end %>>
			<%= link_to "home", root_path, class: active_class?(root_path) %>
			<% @categories.each do |category| %>
				<%= link_to category.title, member_path(category.id), class: active_class?(member_path(category.id)) %>
			<% end %>
		</div>
	</div>
	
	<div class="shadow"></div>
</div>

app/views/elements/modals/_ajax_complete.html.erb
<div class="info"><%= msg %></div>
<% if (!local_assigns[:form].nil?) %>
	<%= render :partial => form %>
<% end %>

app/views/elements/modals/_new_broadcast.html.erb
<div class="body">
	<%= form_for(@new_broadcast, :remote => true, :html => {:id => "broadcast"}) do |f| %>
		Name: <%= f.text_field :name, :required => true %><br/><br/>
		Public? <%= f.check_box :public %><br/><br/>

		<%= f.submit "Create Broadcast", :confirm => "Are you Sure?" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Video Conferencing App</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag params[:controller], "data-turbolinks-track" => true %>  
  <%= csrf_meta_tags %>
  
</head>
<body>
	<div class="page_wrapper">
		<%= render "elements/header" %>
		<div class="main content_wrapper">
			<%= yield %>
		</div>
	</div>

	<%= render "elements/footer" %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>  
	<%= javascript_include_tag params[:controller], "data-turbolinks-track" => true %>
</body>
</html>