config/routes.rb
VideoDemo::Application.routes.draw do
  
  root :to => "members#index"
  
  devise_for :users
  devise_scope :user do
	get "/login" => "devise/sessions#create", :method => "get"
	get "/register" => "devise/registrations#new", :method => "get"
	get "/logout" => "devise/sessions#destroy", :method => "delete"
  end

  resources :profile, :only => ['update']
   
  resources :users, :only => ['index', 'show'] do
	resources :schedules, :only => ['index'] do
		resources :bookings, :only => ['create'], :path_names => { create: 'book' }
	end
	resources :categories, :only => ['update', 'destroy']
  end
  resources :broadcasts, :only => ['create', 'show', 'destroy']
  resources :members, :only => ['index', 'show']
  resources :portfolio, :only => ['create', 'update', 'destroy']
  resources :schedules, :only => ['create', 'update', 'destroy']
  #resources :bookings, :only => ['update', 'destroy']


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
	user ||= User.new # guest user
	
	if user.admin?
		can :manage, :all
	else
		can :read, :all
	end
	
  end
  
end

app/models/booking.rb
class Booking < ActiveRecord::Base

	belongs_to :user, :class_name => 'User'
	has_and_belongs_to_many :schedules, :class_name => 'Schedule'
	
end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base

	belongs_to :user, :class_name => 'User'
	
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :users, :class_name => 'User'
end

app/models/credit.rb
class Credit < ActiveRecord::Base
	belongs_to :user, :class_name => 'User', :foreign_key => 'id'
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

	self.table_name = 'portfolio'
	belongs_to :user, :class_name => 'User'
	
	has_attached_file :cover_image,
		:default_url => "/images/missing.png",
		:storage => :s3,
		:bucket => 'video-conference-demo'

	
	def cover_image_url
        cover_image.url(:original)
    end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	
	has_one :user, :class_name => 'User', :foreign_key => 'user_id'
	
	has_attached_file :avatar,
		:default_url => "/images/missing.png",
		:storage => :s3,
		:bucket => 'video-conference-demo'

	def avatar_url
        avatar.url(:original)
    end

end

app/models/role.rb
class Role < ActiveRecord::Base
   has_and_belongs_to_many :users, :class_name => 'User'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

	belongs_to :user, :class_name => 'User'
	has_and_belongs_to_many :bookings, :class_name => 'Booking'
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
		 
   has_and_belongs_to_many :role, :class_name => 'Role'
   has_one :profile, :class_name => 'Profile', :foreign_key => 'user_id'
   has_many :credits, :class_name => 'Credit', :foreign_key => 'user_id'
   has_and_belongs_to_many :categories, :class_name => 'Category'
   has_many :broadcasts, :class_name => 'Broadcast', :foreign_key => 'user_id'
   has_many :portfolios, :class_name => 'Portfolio', :foreign_key => 'user_id'
   has_many :schedules, :class_name => 'Schedule', :foreign_key => 'user_id'
   has_many :bookings, :class_name => 'Booking'
   
   before_create :role_detect
   before_create :profile_detect
   
   private
   def role_detect
		if self.role.blank?
			self.role << Role.find('3')
		end
   end
   
   private 
   def profile_detect
		build_profile 
   end

   
end

app/models/video.rb
class Video < ActiveRecord::Base

	belongs_to :user, :class_name => 'User'
	validates :name, presence: true
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate_user!, :except => ['show']

	def index
		@user = User.find(current_user.id)
		@credits = @user.credits.sum('value')
		@role = @user.role
		@profile = @user.profile
		@broadcasts = @user.broadcasts.reject {|a| a.id == "" }
		@portfolio = @user.portfolios
		@schedules = @user.schedules
		
		@new_broadcast = @user.broadcasts.new
		@new_categories = Category.all - @user.categories
		
	end
	
	def show
		@user = User.find(params[:id])
		@profile = @user.profile
		@broadcasts = @user.broadcasts
		@portfolio = @user.portfolios
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	#Returns Current Class for Nav Menu
	def active_class?(path)
	  "current" if current_page?(path)
	end
	
	#Returns name or email if name not present
	def name?(user)
		if (!user.profile.name) 
			user.email 
		else
			user.profile.name
		end
	end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/users/_new_broadcast.html.erb

<!-- Create Broadcast Popover -->
<div class="title">
	<%= link_to image_tag('modal_close.png'), "#", :class => "modal_close" %>
	create new broadcast
</div>
<div class="body">
	<%= form_for(@new_video, :remote => true, :html => {:id => "broadcast"}) do |f| %>
		Name: <%= f.text_field :name %><br/><br/>
		Public? <%= f.check_box :public %><br/><br/>

		<%= f.submit "Create Broadcast", :confirm => "Are you Sure?" %>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="profile">

	<div class="options">
	
		<div class="public">
			<%= form_for :upload, :html => {:multipart => true}, url: profile_path(current_user.id), :method => :patch, :remote => true, :id => "public_form" do |f| %>
				<%= f.check_box :public, :checked => @user.profile.public %>
			<% end %>
		</div>
		
		<div class="verified"><%= link_to image_tag('profile/verified.png'), root_path  %></div>
		<div class="profile_link">
			<%= link_to user_path(@user) do %>
				http://<%= request.host %><strong><%= user_path(@user) %></strong>
			<% end %>
			<%= link_to image_tag('profile/username_edit.png'), root_path %>
		</div>

	</div>

	<div class="items">
		<div class="avatar">		
			<!-- New Avatar Upload Form -->
			<%= form_for :upload, :html => {:multipart => true, :id => "avatar"}, :method => :put, url: profile_path(current_user.id), "data_id" => current_user.id do |f| %>
				<div class="btn btn-success fileinput-button avatar" id="avatar_container">
					<%= f.file_field :avatar, :title => "Upload New" %>
					<%= image_tag(@user.profile.avatar.url, :width=> '100%', :id => "avatar_img", :alt => name?(@user)) %>
				</div>
			<% end %>
			<div class="name"><%= link_to name?(@user), root_path %></div>
		</div>
		
		<div class="description">
			<div class="text">
				<div id="description">
					<%= if (!@user.profile.description.nil?) then @user.profile.description.html_safe else "Please add a description!!!" end %>			
				</div>
				<div class="edit" id="edit_description">
					<%= image_tag('profile/edit.png')  %>
				</div>
			</div>	

			
			<div class="info">
				<div class="registered">registered <strong><%= time_ago_in_words( @user.created_at ) %> ago</strong></div>
			</div>
		</div>
		
		<div class="portfolio">
			<div class="images" id="images">
				<% @user.portfolios.each_with_index do |portfolio, index| %>
					<div class="image"><%= link_to image_tag(portfolio.cover_image.url, :size => "110x110", :title => portfolio.description), portfolio_path(portfolio.id), :method => :delete, :id => portfolio.id %></div>
				<% end %>
			</div>
			<div class="info">
				<div class="text"><strong id="portfolio_count"><%= @user.portfolios.count %></strong>  <%= "portfolio photo".pluralize(@user.portfolios.count) %></div>
				<div class="add_photo">
					<%= form_for :new_portfolio, :html => {:multipart => true, :id => "portfolio"}, :method => :post, url: portfolio_index_path do |f| %>
						<span class="btn btn-success fileinput-button">
							<span><%= image_tag('profile/new_photo.png') %></span>
							<%= f.file_field :cover_image %>
						</span>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	
	<div class="categories">
		<ul>
			<% @user.categories.each do |category| %>
				<li><%= link_to category.title, user_category_path(:id => category.id, :user_id => current_user.id), :class => "category a#{rand(1..3)}", :method => :delete %></li>
			<% end %>
			
			<li class="add">
				<%= image_tag('profile/categories_add.png') %>
				<div class="categories_select">
					<% @new_categories.each do |category| %>
						<%= link_to category.title, user_category_path(:id => category.id, :user_id => current_user.id), :method => :put %>
					<% end %>
				</div>
			<li>
		</ul>
	</div>
</div>

<div class="credits">
	<%= number_to_currency(@credits, unit: "&pound;") %>
</div>
<div class="broadcasts">
	<div class="create"><%= link_to "new broadcast", "#new_broadcast", :id => "create_broadcast", :class => "big_button", :rel => "leanModal" %></div>
</div>

<div class="user_table">
	<% @broadcasts.each do |broadcast| %>
		<%= link_to broadcast.name, broadcast_path(broadcast.id), :method => "get", :class => "broadcast " + cycle('even', 'odd') %>
	<% end %>
</div>



	
<div class="modal" id="new_broadcast">
	<div class="title">
		<%= link_to image_tag('modal_close_white.png'), "#", :class => "modal_close" %>
		create new broadcast
	</div>
	<%= render :partial => 'elements/modals/new_broadcast' %>
</div>

app/views/users/show.html.erb
<div class="member_profile">
	<div class="member_avatar">
		<% if (@user.profile.avatar.present?) %>
			<%= image_tag(@user.profile.avatar.url, :width => "400") %>
		<% end %>
	</div>

	<div class="member_info">
		<div class="title"><%= name?(@user) %></div>
		<div class="sub_info">1563 broadcasts</div>
		<div class="description">
			<%= @profile.description.html_safe %>
		</div>
		<div class="book"><%= link_to "book a slot!", user_schedules_path(@user.id), :id => "book_slot", :class => "big_button" %></div>
	</div>
</div>

<% @broadcasts.each do |broadcast| %>
	<%= link_to "#{broadcast.name}", broadcast_path(:id => broadcast.id), :method => "get" %>
<% end %>

<% if @portfolio %>
	<div class="portfolio">
		<% @portfolio.each do |portfolio|%>
			<%= if(portfolio.cover_image.present?) then image_tag(portfolio.cover_image.url, :size => "175x175") else portfolio.description end %>
		<% end %>
		
		<% if @portfolio.count >= 5 %>
			<div class="more">
				<%= link_to "", root_path %>
			</div>
		<% end %>
	</div>
<% end %>